---
title: "Jumbong Junior"
---

<div class="box">

This website serves as the treasury of my intellectual voyage, housing the jewels of my published articles on Medium, the budding seeds of works in progress, and the pillars of knowledge acquired during my third year in the Risk Management program at the National School of Statistics and Information Analysis in Rennes.

</div>

# Meduim Publications

*Medium is an online publishing platform for sharing ideas, stories, and knowledge through articles written by individuals and organizations.*

- **Credit Scoring modellling approach.**
    - Definition of default and construction of the database.
    - Outliers Identification and Treatment
    - Missing data analysis
    - Database splitting
    - Pre-selection of explanatory variables
    - Methodological Approach To Merge Modalities of qualitative variables
    - Methodological Approach To Discretize Quantitative variables
    - Monotony and Stability
    - Oversampling
    - Logistic Regression
        - Definition
        - Fitting The logistic Regression
        - Evaluation of the logistic Regression
            - Analysis of the statistical significance of the model
            - The overall fit of the model : Likelihhod ratio test
            - Statistical significance of individual regression coefficients: Likelihood ratio test and Z statistic
        - Contribution of variables
    - Model performances
- [Sampling Bias and Class Imbalance (Oversampling and Undersampling) in Maximum-likelihood Logistic Regression](Meduim/RegressionLogistique/bias_sample.qmd){target="_self"}
- <a href="Meduim/RegressionLogistique/bias_sample.qmd" target="_self">Sampling Bias and Class Imbalance (Oversampling and Undersampling) in Maximum-likelihood Logistic Regression</a>



- Résumé de la théorie des valeurs extrêmes ([EVT_resume.pdf](3A/EVT/EVT_resume.pdf))


in Maximum-likelihood Logistic Regression
# Microéconometrie appliquée
- Résumé des méthodes de microéconométrie appliquée enseignée à la promo 2024-2025 Ensai ([applied_micro.pdf](2A/Courses.pdf))

# Apprentissage supervisée

- Advanced Techniques in Machine Learning: Kernel Trick and Support Vector Machines (SVM) ([kernel_and_svm.qmd](3A/Apprentisage-stat/Tp2.qmd))
- Gradient boosting ([gradient_boosting.qmd](3A/Apprentisage-stat/Tp3.qmd))
- Features selection ([features_selection.qmd](3A/Apprentisage-stat/Tp4.qmd))

## Régressions

- Regression linéaire ([regression_lin.qmd](2A/App_sup/reg_lin.qmd))
- Regression ridge et lasso ([lasso_ridge.qmd](3A/Apprentisage-stat/Tp1.qmd))

## Classifications

- Applications des arbres & forêts aléatoires sur un jeu de données ([arbres_&_forets_aleatoires.html](2A/App_sup/arbres_&_forets_aleatoires.html)) </li>

# Learning SAS