{
  "hash": "fa636ae17011d360d628ce8c6cce73a7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \" Bootstrap Confidence Interval\"\nsidebar: auto\nnumber-sections: false\ntoc: true\nauthor:\n  - Jumbong Junior \ncategories: []\ntags: [Bootstrap, Confidence Interval]\ntitle-block-banner: false\nbibliography: references.bib\nformat: \n  html: \n    mainfont: Times New Roman\n    fontsize: 16pt\n\njupyter: python3\nnotice: |\n    @wasserman2013all\n---\n\n\n\n# Introduction\n\nWhen working with data, it very important to assess the uncertainty associated with interest parameter. \nConfidence interval is one of the most popular method to estimate the uncertainty of the parameter. Let's define it :\n\nGiven a sample $\\mathcal{X} = \\{X_1, X_2, \\ldots, X_n\\}$ of size $n$ from a distribution $P$.\n\nGiven $\\theta = \\theta(P)$ $\\in \\Theta$ a real-valued parameter.\n\nLet $\\alpha \\in (0, 1)$ be a confidence level (commonly $\\alpha = 0.05$ for a 95% confidence interval).\n\nA **confidence interval** for $\\theta$ at level $1-\\alpha$, denoted as $IC_{1-\\alpha}(\\theta)$, is a random subset :\n\n$$\n\\mathcal{I}_n(X) = [T_{\\inf}(X), T_{\\sup}(X)]\n$$\n\nof **Θ** such that:\n\n$$\n1 - \\alpha = \\mathbb{P}(\\theta \\in \\mathcal{I}_n(X)).\n$$\n\nThere are serveral methods to estimate the bootstrap confidence interval. In this document, three methods will be presented :\n\n- The normal method\n- The pivotal method\n- The percentile method\n\n# Theoritical Background\n\n\nLet $\\theta_n = \\theta(P_n)$ be a plug-in estimator of $\\theta$. \n\nLet $\\theta_{n,1}^*, ..., \\theta_{n,B}^*$ be the bootstrap replications of $\\theta_n$.\n\nLet $q_{\\alpha/2}$ and $q_{1-\\alpha/2}$ be the $\\alpha/2$ and $1-\\alpha/2$ quantiles of the bootstrap distribution of the sample ($\\theta_{n,1}^*, ..., \\theta_{n,B}^*$).\n\n# The Normal Interval \n\nThis is the simplest method to construct the confidence interval. This method assumes that the sampling distribution\nof the estimator $\\theta_n = \\theta$ is approximately normal. The standard error of the estimator is estimated by the \nbootstrap standard error. The normal interval is given by :\n$$\n\\theta_n \\pm z_{\\alpha/2} \\hat{se}_{boot}\n$$\n\nwhere :\n\n- $\\hat{se}_{boot}$ is the bootsrap estimate of the standard error.\n\n- $z_{\\alpha/2}$ is the $\\alpha/2$ quantile of the standard normal distribution. Many consider $z_{\\alpha/2} = 1.96$ for a 95% confidence interval.\n\nThis interval is not accurate unless the distribution of $T_n$ is close to the normal distribution.\n\n# The Pivotal Intervals\n\nThe pivotal method uses a pivotal statistic $R_n(\\mathcal{X}, \\theta)$ that is a function of the data and the parameter. \n\nExample : Let $\\theta$ be a location parameter for $\\theta_n(\\mathcal{X})$.\n\n\n- $R_n = \\theta_n - \\theta$ pivot\n- $R_n = \\frac{\\theta_n - \\theta}{\\hat{se}_{boot}}$ pivot\n- $R_n = \\beta(\\theta_n) - \\beta(\\theta)$ variance-stabilizing pivot\n\nTo construct this interval, the first step is to determine a pivotal statistic $R_n(\\mathcal{X}, \\theta).$ \nNext, use bootstrap sampling to compute the quantiles $q_{\\alpha/2}$ and $q_{1-\\alpha/2}$ so that :\n$$\nP_p(R_n(\\mathcal{X}, \\theta) \\in [q_{\\alpha/2}, q_{1-\\alpha/2}]) = 1 - \\alpha,\n$$\n\nFinally, the equation is inverted to obtain the confidence interval :\n$$\nR_n(\\mathcal{X}, \\theta) \\in [q_{\\alpha/2}, q_{1-\\alpha/2}] \\Leftrightarrow \\theta \\in [T_{inf}(\\mathcal{X}), T_{sup}(\\mathcal{X})]\n$$\n\nThe algorithm below shows how to construct the confidence interval of the pivot :\n\n::: {.callout-note icon=\"false\"}\n\n### Pivotal Confidence Interval bootstrap\n\n**Variable**:\n\n- $B$ : A large number of bootstrap samples.\n\n**Begin**:\n\nFor $b = 1, 2, \\ldots, B$:\n  \n  - Generate a bootstrap sample $\\mathcal{X}^*_b$ from $\\mathcal{X}$.\n  - Compute $r_n^{*b} = R_n(\\mathcal{X}^{*b})$, the bootstrap replication of $R_n(\\mathcal{X})$.\n\nEnd for.\n\nReturn the quantiles $q_{\\alpha/2}$ and $q_{1-\\alpha/2}$ of the bootstrap distribution of $r_n^{*b}$.\nThey are also the order statistics $\\lceil B \\alpha \\rceil$ and $\\lceil B (1-\\alpha) \\rceil$ of $r_n^{*b}$.\n:::\n\nWhen the pivot is $R_n = \\theta_n - \\theta$, the  bootstrap pivotal confidence interval is :\n\n$$\nC_n  = [2\\theta_n-q_{\\alpha/2}, 2\\theta_n-q_{1-\\alpha/2}]\n$$\n\nwhere $q_{\\alpha/2}$ and $q_{1-\\alpha/2}$ are the $\\alpha/2$ and $1-\\alpha/2$ quantiles of the bootstrap distribution of the sample ($\\theta_{n,1}^*, ..., \\theta_{n,B}^*$).\n\n\n\n# The percentile intervals\n\nThe percentile method is the conceptually straightforward method to construct the confidence interval.\nThe quantiles distribution of the bootstrap replications of the estimator $\\theta_n$ are used to construct the confidence interval :\n\n$$\nC_n = [\\theta_{\\lceil B \\alpha/2 \\rceil}, \\theta_{\\lceil B (1-\\alpha/2) \\rceil}]\n$$\n\nwhere $\\theta_{\\lceil B \\alpha/2 \\rceil}$ and $\\theta_{\\lceil B (1-\\alpha/2) \\rceil}$ are the $\\lceil B \\alpha/2 \\rceil$ and $\\lceil B (1-\\alpha/2) \\rceil$ \norder statistics of the bootstrap distribution of the sample ($\\theta_{n,1}^*, ..., \\theta_{n,B}^*$).\n\nThe algorithm below shows how to construct the confidence interval of the pivot :\n\n::: {.callout-note icon=\"false\"}\n\n### Percentile Confidence Interval bootstrap\n\n**Variable**:\n\n- $B$ : A large number of bootstrap samples.\n\n**Begin**:\n\nFor $b = 1, 2, \\ldots, B$:\n  \n  - Generate a bootstrap sample $\\mathcal{X}^*_b$ from $\\mathcal{X}$.\n  - Compute $\\theta^{*b} = \\theta(\\mathcal{X}^{*b})$, the bootstrap replication of $\\theta(\\mathcal{X})$.\n\nEnd for.\n\nReturn the quantiles $\\theta_{\\lceil B \\alpha \\rceil}$ and $\\theta_{\\lceil B (1-\\alpha) \\rceil}$ of the bootstrap distribution of $\\theta^{*b}$.\n:::\n\n# Application in python\n\nLet's illustrate these three methods with two samples X1 =94,38,23,197,99,16,141 and X2 = 52,10,40,104,50,27,146,31,46.\nWe are interested in the difference between medians. \n\n::: {#03184ec2 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\n\nnp.random.seed(123)\n\nX1 = np.array([94,38,23,197,99,16,141])\nX2 = np.array([52,10,40,104,50,27,146,31,46])\nalpha = 0.05\nn1 = len(X1)\nn2 = len(X2)\n\n# Compute the difference of the median\ntheta_n = np.median(X1) - np.median(X2)\nB = 1000\ntboot = np.empty(B)\n\nfor b in range(B):\n    X1b = np.random.choice(X1, n1, replace=True)\n    X2b = np.random.choice(X2, n2, replace=True)\n    tboot[b] = np.median(X1b) - np.median(X2b)\n\n#######################################################################\n# Normal interval\n#######################################################################\nseboot = np.std(tboot)\n\nNormal_inf = round(theta_n - 1.96*seboot,2)      \nNormal_sup = round(theta_n + 1.96*seboot,2)\nNormal = [Normal_inf, Normal_sup]\n\n#######################################################################\n# Pivot interval : theta - theta_n\n#######################################################################\npivot_inf = np.quantile(tboot, 0.025)\npivot_sup = np.quantile(tboot, 0.975)\nPivot = [round(2*theta_n - pivot_sup,2), round(2*theta_n - pivot_inf,2)]\n\n#######################################################################\n# Percentile interval\n#######################################################################\npercentile_inf = np.quantile(tboot,0.025)\npercentile_sup = np.quantile(tboot,0.975)\nPercentile = [round(percentile_inf,2), round(percentile_sup,2)]\n\n#######################################################################\n# Write output in a table with the first column, the Method and the second\n# column the 95% Interval\n#######################################################################\noutput = pd.DataFrame({'Method': ['Normal', 'Pivot', 'Percentile'],\n                       '95% Interval': [Normal, Pivot, Percentile]})\nprint(f\"The point estimate of the difference of the median is {theta_n}\")\nprint(f\"The bootstrap standard error is {seboot}\")\nprint(output)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe point estimate of the difference of the median is 48.0\nThe bootstrap standard error is 39.68365527518855\n       Method      95% Interval\n0      Normal  [-29.78, 125.78]\n1       Pivot     [-5.0, 125.0]\n2  Percentile    [-29.0, 101.0]\n```\n:::\n:::\n\n\nThe point estimate is 48.0, the bootstrap standard error is 39.68 and the resulting approximate 95 percent confidence intervals are as follows:\n\n# Conclusion\n\nAll the confidence intervals are approximate. All three intervals have the same level of accuracy. \nThey are are more accurate bootstrap confidence intervals but they are more complicated and computationally intensive.\n\n## References\n\n::: {#refs}\n\n:::\n\n",
    "supporting": [
      "ConfidenceInterval_files"
    ],
    "filters": [],
    "includes": {}
  }
}